### ISSUE TITLE
问一些关于AcToken的问题

### ISSUE THREAD

**Issue by taotaolin** [maxnoodles/js_decrypt#1]
我这边具体使用上发现Actoken有b,d两个请求，里面的算法好像使用了指纹还是浏览器的数据导致我拿出来的JS无法使用，方便告知一下思路么？不方便也可以私聊

**Comment by maxnoodles** [comment]
我记得当时这个 Actoken 的值是不校验的，d 值可以看看我其中一个 my_d 的文件，后面发现 Actoken 没校验就没去再去逆向 b 了，可能帮不上忙，不好意思
